webtalk_init -webtalk_dir /home/code/verilog/Sirius/Sirius_vivado/Sirius_vivado.sim/sim_1/behav/xsim/xsim.dir/Sirius_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 28 19:19:31 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bab87005-6d1c-4963-a025-bb217252f5aa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "abbf8912a37f46e79f74f429b9889872" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "133" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Kali" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Kali GNU/Linux Rolling" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1568.958 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "120480_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3135646605 -regid "" -xml /home/code/verilog/Sirius/Sirius_vivado/Sirius_vivado.sim/sim_1/behav/xsim/xsim.dir/Sirius_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/code/verilog/Sirius/Sirius_vivado/Sirius_vivado.sim/sim_1/behav/xsim/xsim.dir/Sirius_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/code/verilog/Sirius/Sirius_vivado/Sirius_vivado.sim/sim_1/behav/xsim/xsim.dir/Sirius_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
